# Generated by Django 4.1.6 on 2023-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiProyecto', '0004_producto_descripcion_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.jpg', upload_to='MiProyecto\\static\\productos'),
        ),
    ]
